[package]
name = "ai-httpd"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
openai = { version = "1.1.1", features = ["rustls"] }
tokio = { version = "1.47.1", features = ["full"] }
